FROM mraa-base

# Update apt-get
RUN apt-get -y update && \
  # Python 2 Build Dependencies
  apt-get -y --no-install-recommends install python python-dev \
  # Python 3 Build Dependencies
  python3 python3-dev

# Set Workdir
WORKDIR $MRAA_SRC_DIR

CMD bash
